baseURL: "https://sherlockramos.life"
languageCode: "pt-br"
title: "SherlockRamos"
theme: "PaperMod"

# Hugo caches
caches:
  images:
    dir: ":cacheDir/images"

# Markdown features
markup:
  goldmark:
    renderer:
      unsafe: true
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
  tableOfContents:
    startLevel: 2
    endLevel: 3

# Taxonomies
taxonomies:
  category: categories
  tag: tags

# Menus
menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 1
    - identifier: blog
      name: Blog
      url: /posts/
      weight: 2
    - identifier: contact
      name: Contato
      url: /contact/
      weight: 3

params:
  env: production
  description: "Blog sobre IA, estudos e abobrinhas diversas."
  author: "Sherlock Ramos"
  assets:
    theme_color: "#131D4F"
    customCSS:
      - css/custom.css
  profileMode:
    enabled: true
    title: "SherlockRamos"
    subtitle: "Bem-vindo ao blog do Sherlock Ramos"
    imageUrl: "https://pbs.twimg.com/profile_images/1848910652808613888/r81-u5pP_400x400.jpg"
    imageTitle: "Foto de Sherlock Ramos"
    imageWidth: 120
    imageHeight: 120
    buttons:
      - name: "Twitter"
        url: "https://x.com/GatoMaconhado_"
      - name: "GitHub"
        url: "https://github.com/profgabrielramos-ai"
  socialIcons:
    - name: "GitHub"
      url: "https://github.com/profgabrielramos-ai"
    - name: "Twitter"
      url: "https://twitter.com/GatoMaconhado_"
    - name: "Instagram"
      url: "https://instagram.com/prof.gabrielramos"
